import type { FileAccessError } from "contract";
import type { Messages } from "use-intl";
export const sourceBlockerKeys: Record<FileAccessError, keyof Messages> = {
  "source-unknown": "filesBlockerSourceUnknown",
  "source-protected": "filesBlockerSourceProtected",
  "source-shared": "filesBlockerSourceShared",
  "source-ownership-unknown": "filesBlockerSourceOwnershipUnknown",
  "source-read-only": "filesBlockerSourceReadOnly",
  "backup-directory-protected": "filesBlockerBackupDirectoryProtected",
  "not-mounted": "filesBlockerNotMounted",
  "agent-read-only": "filesBlockerAgentReadOnly",
  "not-allowlisted": "filesBlockerNotAllowlisted",
  "name-not-usable-as-directory": "filesBlockerNameNotUsableAsDirectory",
  "invalid-compose-file-name": "filesBlockerInvalidComposeFileName",
  "compose-project-name-missing-or-invalid": "filesBlockerComposeProjectNameMissingOrInvalid",
  "project-dir-outside-base-path": "filesBlockerProjectDirOutsideBasePath",
  "self-management-locked": "filesBlockerSelfManagementLocked",
  "compose-file-missing": "filesBlockerComposeFileMissing",
  "compose-anchor-labels-missing": "filesBlockerComposeAnchorLabelsMissing",
  "compose-anchor-outside-base-path": "filesBlockerComposeAnchorOutsideBasePath",
  "compose-anchor-file-ambiguous": "filesBlockerComposeAnchorFileAmbiguous",
  "directory-taken": "filesBlockerDirectoryTaken",
  "stack-service-not-allowlisted": "filesBlockerStackServiceNotAllowlisted",
  "externally-managed": "filesBlockerExternallyManaged",
  "compose-hash-missing": "filesBlockerComposeHashMissing",
  "confirmation-missing": "filesBlockerConfirmationMissing",
  "too-many-streams": "filesBlockerTooManyStreams",
  "stack-busy": "filesBlockerStackBusy",
  "path-empty": "filesBlockerPathEmpty",
  "path-absolute": "filesBlockerPathAbsolute",
  "path-traversal": "filesBlockerPathTraversal",
  "path-invalid-characters": "filesBlockerPathInvalidCharacters",
  "path-blocked": "filesBlockerPathBlocked",
  "path-outside": "filesBlockerPathOutside",
  "file-replaced": "filesBlockerFileReplaced",
  "not-readable": "filesBlockerNotReadable",
  "not-writable": "filesBlockerNotWritable",
  "wrong-kind": "filesBlockerWrongKind",
  "not-a-text-file": "filesBlockerNotATextFile",
  "too-large": "filesBlockerTooLarge",
  "already-exists": "filesBlockerAlreadyExists",
  "file-changed-externally": "filesBlockerFileChangedExternally",
  "expected-hash-missing": "filesBlockerExpectedHashMissing",
  "busy": "filesBlockerBusy",
};
