import { DEFAULT_BIND_BASE_PATH, type HostArchiveInput } from "./host-archive-input.js";

// Vorlage der `.env` im Archiv eines Arms.
//
// Herkunft: dashboard-docker-agent@v0.18.1, deploy/remote-wireguard/.env.example.
// Abweichungen: der Image-Verweis ist gepinnt statt `:latest` (AGENTS.md), und
// `DOCKER_AGENT_TUNNEL_CIDR` trägt das Netz DIESES Hubs statt des Quellsystems.
//
// ⚠️ Diese Datei trägt zwei Geheimnisse. Sie gehört auf dem Zielhost auf 0600,
// und der Hub hat sie nach dem Ausliefern nicht mehr in dieser Form.

export function renderEnvFile(input: HostArchiveInput): string {
  const lines = [
    `# Generated by the dashboard hub for host ${input.host.name} (${input.host.kind}).`,
    "#",
    "# WARNING: contains secrets. chmod 600. Never put this in a repository.",
    "",
    "# Pinned to a SemVer tag — no `latest`. Going back to an older build is",
    "# this one line plus `docker compose up -d`.",
    `DOCKER_AGENT_IMAGE=${input.agent.image}`,
    "",
    "# The secret the hub authenticates to the agent with. It is valid for this",
    "# host only; a new archive brings a new one.",
    `DOCKER_AGENT_SECRET=${input.agent.secret}`,
    "",
    "# The tunnel address assigned to this host. The agent listens here and",
    "# nowhere else (DOCKER_AGENT_REQUIRE_TUNNEL_BIND=true in docker-compose.yml).",
    `DOCKER_AGENT_HOST=${input.host.tunnelAddress}`,
    "",
    "# WARNING: the agent's own default is 10.253.0.0/24, a different network.",
    "# Without this line it rejects the registration URL below at startup.",
    `DOCKER_AGENT_TUNNEL_CIDR=${input.hub.tunnelCidr}`,
    "",
    "# The one-time registration with the hub. `http` is correct and not an",
    "# oversight: the connection runs inside the tunnel, where the transport",
    "# itself is the encryption. The token is spent on the first success.",
    `DOCKER_AGENT_REGISTRATION_URL=${input.registration.url}`,
    `DOCKER_AGENT_REGISTRATION_TOKEN=${input.registration.token}`,
    "",
    "# Below this path the agent may create and read bind mounts. If this",
    "# host's compose projects live somewhere else, change the path here —",
    "# otherwise the agent rejects them.",
    `DOCKER_AGENT_BIND_BASE_PATH=${input.host.bindBasePath ?? DEFAULT_BIND_BASE_PATH}`,
    "",
    "# The group id that owns the Docker socket on THIS host.",
    "#   stat -c %g /var/run/docker.sock",
    "# Read off the socket rather than looked up by group name — for the same",
    "# reason the hub's own scripts/bootstrap.sh does it this way: `getent",
    "# group docker` returns nothing where no group of that name exists, and it",
    "# returns the wrong number where the socket belongs to a group other than",
    "# the one that carries the name. Both end in the same place — the agent",
    "# starts and is not allowed to read the socket.",
    ...(input.host.dockerGid === null
      ? [
          "#",
          "# WARNING: fill this in by hand. The hub does not have the number for",
          "# this host. Left empty, the stack does not start — and names exactly",
          "# this variable when it refuses."
        ]
      : ["#", "# Filled in when this host was created in the hub; the command above is the cross-check."]),
    // ⚠️ `=== null` und nicht `??` auf den Wahrheitswert: 0 ist die Gruppe
    // root, und `input.host.dockerGid || ""` schriebe dafür eine leere Zeile.
    `DOCKER_GID=${input.host.dockerGid === null ? "" : String(input.host.dockerGid)}`
  ];
  return lines.join("\n") + "\n";
}
