import type { HostArchiveInput } from "./host-archive-input.js";

// Vorlage der `docker-compose.yml` im Archiv eines Arms.
//
// Herkunft: dashboard-docker-agent@v0.18.1, deploy/remote-wireguard/docker-compose.yml.
// Übernommen sind Dienstzuschnitt, Härtung und die Healthchecks. Abweichungen
// gegenüber der Vorlage, jede mit Grund:
//
//   1. Der Block für private Registries am Watcher (DOCKER_CONFIG,
//      DOCKER_AGENT_DOCKERCFG_HOST_PATH, `user: "0"`, DAC_OVERRIDE) fällt
//      vollständig weg. Das Agent-Image ist öffentlich; ein Archiv, das eine
//      Anmeldung an einer Registry voraussetzt, verlangt vom Betreiber ein
//      Token, das es hier nicht gibt.
//   2. `pull_policy: always` becomes `missing`. The reference is pinned to a
//      SemVer tag that the release workflow never overwrites, so there is
//      nothing to pull again, and `always` would tie every restart to the
//      registry being reachable. A host that comes up without network after a
//      power cut would not start at all otherwise.
//   3. `DOCKER_AGENT_TUNNEL_CIDR` steht auf `:?` statt auf einem Vorgabewert.
//      Die Vorgabe des Agenten ist das Netz des Quellsystems (10.253.0.0/24);
//      eine fehlende Zeile in der `.env` ergäbe damit einen Agenten, der still
//      im falschen Netz sucht statt laut zu fehlen.
//
// ⚠️ Zeilen entstehen als Feld und werden mit "\n" verbunden. Ein
// Zeilenumbruch in einem Template-Literal übernähme die Zeilenenden DIESER
// Datei — auf einem Rechner mit CRLF ginge das ungesehen ins Archiv.

const SERVICE_WIREGUARD = "wireguard";
const SERVICE_AGENT = "docker-agent";
const SERVICE_WATCHER = "watcher";

// The image reference stands in the `.env`; only the variable's name stands
// here. Each service can also be overridden on its own (AGENTS.md, "Images") —
// the sidecar and the watcher run from the same image as the agent, but they
// do not have to.
const IMAGE = "${DOCKER_AGENT_IMAGE:?DOCKER_AGENT_IMAGE is missing}";
const IMAGE_WIREGUARD = `\${DOCKER_AGENT_WIREGUARD_IMAGE:-${IMAGE}}`;
const IMAGE_WATCHER = `\${DOCKER_AGENT_WATCHER_IMAGE:-${IMAGE}}`;

// Compose project of the generated stack. It prefixes the state volume, and
// `SYSTEM_PROJECTS` in server/src/domain/containers/system-containers.ts must
// list it. `LEGACY_COMPOSE_PROJECT` is the name of archives up to v0.32.0; the
// README tells the operator to stop that project before the new one starts.
export const COMPOSE_PROJECT = "docklet-hub-agent-remote";
export const LEGACY_COMPOSE_PROJECT = "dashboard-docker-agent-remote";

export function renderComposeFile(input: HostArchiveInput): string {
  const lines = [
    "# Generated by the dashboard hub for host " + input.host.name + ".",
    "#",
    "# Template: dashboard-docker-agent@v0.18.1, deploy/remote-wireguard.",
    "#",
    "# WARNING: do not edit anything here by hand that also lives in the hub. A",
    "# new archive replaces this file completely, and the hub knows nothing",
    "# about a change made here.",
    `name: ${COMPOSE_PROJECT}`,
    "",
    "services:",
    "  # The hub end of this tunnel is a sidecar in the hub stack. This one is",
    "  # the far end and the ONLY service with NET_ADMIN: the capability applies",
    "  # to its own network namespace, which the agent shares with it.",
    `  ${SERVICE_WIREGUARD}:`,
    `    image: ${IMAGE_WIREGUARD}`,
    "    pull_policy: missing",
    "    restart: unless-stopped",
    '    user: "0:0"',
    '    command: ["/usr/local/bin/wireguard-sidecar"]',
    "    cap_add: [NET_ADMIN]",
    '    security_opt: ["no-new-privileges:true"]',
    "    read_only: true",
    '    tmpfs: ["/run", "/tmp"]',
    "    volumes:",
    "      - ./wg0.conf:/etc/wireguard/wg0.conf:ro",
    "    healthcheck:",
    '      test: ["CMD", "wg", "show", "wg0"]',
    "      interval: 5s",
    "      timeout: 3s",
    "      retries: 12",
    "",
    "  # The agent has no network namespace of its own and therefore no route",
    "  # out that bypasses the tunnel. If the sidecar is down, so is the agent —",
    "  # that is what depends_on/service_healthy is for.",
    `  ${SERVICE_AGENT}:`,
    `    image: ${IMAGE}`,
    "    pull_policy: missing",
    "    restart: unless-stopped",
    `    network_mode: "service:${SERVICE_WIREGUARD}"`,
    "    depends_on:",
    `      ${SERVICE_WIREGUARD}:`,
    "        condition: service_healthy",
    "    env_file: [.env]",
    "    environment:",
    "      DOCKER_AGENT_HOST: ${DOCKER_AGENT_HOST:?DOCKER_AGENT_HOST is missing}",
    `      DOCKER_AGENT_PORT: "${input.agent.port}"`,
    '      DOCKER_AGENT_REQUIRE_TUNNEL_BIND: "true"',
    "      # WARNING: without this line the agent assumes 10.253.0.0/24 — the",
    "      # source system's network — and rejects this hub's registration URL at",
    "      # startup.",
    "      DOCKER_AGENT_TUNNEL_CIDR: ${DOCKER_AGENT_TUNNEL_CIDR:?DOCKER_AGENT_TUNNEL_CIDR is missing}",
    "      DOCKER_AGENT_REGISTRY_FILE: /state/registry.json",
    "      DOCKER_AGENT_MONITOR_FILE: /state/monitors.json",
    "      DOCKER_AGENT_AUDIT_FILE: /state/audit.jsonl",
    "      DOCKER_AGENT_BIND_BASE_PATH: ${DOCKER_AGENT_BIND_BASE_PATH:?DOCKER_AGENT_BIND_BASE_PATH is missing}",
    "    volumes:",
    "      - /var/run/docker.sock:/var/run/docker.sock:ro",
    "      - docker-agent-state:/state",
    "      - ${DOCKER_AGENT_BIND_BASE_PATH}:${DOCKER_AGENT_BIND_BASE_PATH}",
    "    group_add:",
    '      - "${DOCKER_GID:?DOCKER_GID is missing}"',
    "    cap_drop: [ALL]",
    '    security_opt: ["no-new-privileges:true"]',
    "    read_only: true",
    '    tmpfs: ["/tmp"]',
    "    # Without a healthcheck, an agent that aborted during startup still",
    "    # counts as running to Docker — restart: unless-stopped then brings it",
    "    # up in a silent loop. The check uses the tunnel address and not",
    "    # 127.0.0.1: with tunnel binding enforced the agent listens there only.",
    "    healthcheck:",
    `      test: ["CMD", "wget", "--spider", "-q", "http://\${DOCKER_AGENT_HOST}:${input.agent.port}/health"]`,
    "      interval: 30s",
    "      timeout: 5s",
    "      retries: 3",
    "      start_period: 20s",
    "",
    "  # The watcher performs the agent update: during the swap the engine",
    "  # stops the agent container and every process inside it — the agent",
    "  # cannot replace itself. The watcher's input is a file in the shared",
    "  # /state, its way out is the socket. Hence network_mode: none and no",
    "  # env_file: it has neither a port nor a route nor a secret.",
    "  #",
    "  # WARNING: it swaps the agent ONLY, never itself. After an update it",
    "  # keeps running the previous build until a new archive or a",
    "  # `docker compose up -d` carries it along. This service ages silently.",
    `  ${SERVICE_WATCHER}:`,
    `    image: ${IMAGE_WATCHER}`,
    "    pull_policy: missing",
    "    restart: unless-stopped",
    '    command: ["node", "dist/watcher.js"]',
    '    network_mode: "none"',
    "    environment:",
    "      DOCKER_AGENT_SELF_UPDATE_DIR: /state/selbstupdate",
    "    volumes:",
    "      - /var/run/docker.sock:/var/run/docker.sock:ro",
    "      - docker-agent-state:/state",
    "    group_add:",
    '      - "${DOCKER_GID:?DOCKER_GID is missing}"',
    "    cap_drop: [ALL]",
    '    security_opt: ["no-new-privileges:true"]',
    "    read_only: true",
    '    tmpfs: ["/tmp"]',
    "",
    "volumes:",
    "  docker-agent-state:"
  ];
  return lines.join("\n") + "\n";
}
