import type { HostArchiveInput } from "./host-archive-input.js";

// Vorlage der `wg0.conf` im Archiv eines Arms — die Gegenseite zu dem
// `[Peer]`-Eintrag, den der Hub für diesen Host in seinem Sidecar führt.
//
// ⚠️ Der erzeugte Text ist ENGLISCH wie die drei anderen Dateien des Pakets,
// die Kommentare hier bleiben deutsch (AGENTS.md, „Sprache", die
// Ausnahmeliste; #92). Diese Datei ist beim ersten Durchgang übersehen worden
// und wäre als einzige deutsch an den fremden Host gegangen — gefunden von der
// unabhängigen Prüfung, nicht vom Bauenden.
//
// Muster: dashboard-docker-agent@v0.18.1, deploy/remote-wireguard.
//
// ⚠️ Diese Datei trägt den privaten Schlüssel des Arms, und zwar an der
// einzigen Stelle, an der er überhaupt existiert: der Hub speichert ihn nicht.
// Wer sie verliert, bekommt kein zweites Exemplar, sondern ein neues Archiv.
//
// Nicht zu verwechseln mit `wireguard-config.ts`: das ist die Peer-Liste der
// HUB-Seite. Beide beschreiben dieselbe Beziehung aus zwei Richtungen.

// Der Keepalive hält die Zuordnung in einer NAT-Tabelle offen. Ohne ihn steht
// der Tunnel, bis der Arm eine Weile still ist — danach kommt der Hub nicht
// mehr zu ihm durch, und der Arm merkt davon nichts, weil er selbst noch
// senden kann.
const PERSISTENT_KEEPALIVE_SECONDS = 25;

export function renderTunnelConfig(input: HostArchiveInput): string {
  const prefix = input.hub.tunnelCidr.split("/")[1];
  const lines = [
    `# Generated by the dashboard hub for host ${input.host.name}.`,
    "# Contains this arm's private key: chmod 600.",
    "[Interface]",
    `PrivateKey = ${input.agent.privateKey}`,
    `Address = ${input.host.tunnelAddress}/${prefix}`,
    "",
    "# The hub. AllowedIPs deliberately names a single address and not the whole",
    "# tunnel network: this arm talks to the hub and to no other arm.",
    "[Peer]",
    `PublicKey = ${input.hub.publicKey}`,
    `Endpoint = ${input.hub.endpoint}`,
    `AllowedIPs = ${input.hub.hubAddress}/32`,
    `PersistentKeepalive = ${PERSISTENT_KEEPALIVE_SECONDS}`
  ];
  return lines.join("\n") + "\n";
}
